sonata_seo:
    encoding:         UTF-8
    page:
        title:            Mealmatch Social-Dining | Platform. Marktplatz. Community.
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             "mealmatch menschen essen zusammen social dining social-dining"
                description:          "Mealmatch ist eine Online-Community-Plattform, die Menschen weltweit zu einem gemeinsamen Meal zusammenbringt."
                robots:               "index, follow"

            property:
                # Facebook application settings
                #'fb:app_id': "%facebook_app_id%"
                #'fb:admins':          admin1, admin2
                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Mealmatch Social-Dining | Platform. Marktplatz. Community.
                'og:description':     Mealmatch Social-Dining | Platform. Marktplatz. Community.
                'og:type': "website"

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            'xmlns:fb':           "http://www.facebook.com/2008/fbml"

#    sitemap:
#        services:
#            - api.sitemap
#
#        doctrine_orm:
#            - { group: "meals", foo: bar }
#            #- { connection: doctrine.dbal.default_connection, route: public_homemeal_show, parameters: {id: null}, query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM base_meal WHERE leaf = 1 AND status like 'RUNNING'" }
#            # media
#            # - { types: [image], connection: doctrine.dbal.default_connection, route: sonata_media_view,       parameters: {id: null},                               query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM media__media WHERE enabled = true" }
#            # blog post
#            # - { group: "news",  connection: doctrine.dbal.default_connection, route: sonata_news_view,        parameters: {permalink: null},                        query: "SELECT CONCAT_WS('/', YEAR(created_at), MONTH(created_at), DAY(created_at), slug) as permalink , updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM news__post WHERE enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
#            # page - works only for one site, please adapt the code if required
#            # - {                 connection: doctrine.dbal.default_connection, route: page_slug,               parameters: {path: null},                             query: "SELECT url as path, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM page__snapshot WHERE route_name = 'page_slug' AND enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW()) AND (publication_date_end IS NULL OR publication_date_end >= NOW())" }
#            # product categories
#            # - {                 connection: doctrine.dbal.default_connection, route: sonata_catalog_category, parameters: {category_id: null, category_slug: null}, query: "SELECT id as category_id, slug as category_slug, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM classification__category WHERE enabled = true" }
#            # products
#            # - {                 connection: doctrine.dbal.default_connection, route: sonata_product_view,     parameters: {productId: null, slug: null},            query: "SELECT id as productId, slug, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM product__product WHERE enabled = true" }