imports:
#    - { resource: config_local.yml } <-- local developer setting
    - { resource: config.yml }
    - { resource: parameters_dev.yml }




# #########################################
# Doctrine Configuration
# #########################################
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: '5.5'
    orm:
        metadata_cache_driver: array
        result_cache_driver: array
        query_cache_driver: array

# #########################################
# Webpack / Encore  - UI assets
# #########################################
webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/web/static/dev'

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    # if you dont have memcache set use the next 2 lines to use local file session
    session:
        handler_id: ~
    assets:
        json_manifest_path: '%kernel.project_dir%/web/static/dev/manifest.json'

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: [mealmatch, mangopay]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ["!event", "!doctrine", "!mealmatch"]

        mealmatch:
            level: error
            type:  service # stream
            channels: [mealmatch, mangopay] # doctrine
            id: apibundle.services.logentry_handler

        mealmatch_log:
            # log all messages (since debug is the lowest level)
            level:    debug
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_mealmatch.log"
            channels: [mealmatch]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        chromephp:
            type:   chromephp
            level:  error

        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine", "!event"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine", "mealmatch"]

swiftmailer:
    delivery_address: deinname@mealmatch.de
