# Mealmatch 2017
# Configuration for target host
# meal-match.com
parameters:
    mm:
        ga_tracking_id: UA-88829351-1
        website_online: '%env(MM_WEBSITE_ONLINE)'
        env(MM_WEBSITE_ONLINE): true
    mm_features:
        messaging: false
        autobahn: false
        websockets: false
        facebook_login: false
        variant_default: b

    # Memcached
    session_memcache_prefix: mm_
    session_memcache_expire: 14400
    session_memcache_host_1: memcachecluster.frbit.com
    session_memcache_port_1: 11211

    ## security channel
    mm_security_channel: 'http'

    ## The Fee's of Mealmatch
    mm_fee_homemeal: 0.15
    mm_fee_promeal: 0.15

    # WWW -> MMWebFront and all default routes? @todo: not used yet ...
    # Defaults to www.mealmatch.de
    www_req.subdomain: www|pro|restaurant|home|mealmatch-stage|mealmatch
    www_def.subdomain: www
    www_req.domain: mealmatch|mealmatchapp|frb
    www_def.domain: mealmatch
    www_req.toplevel: de|io
    www_def.toplevel: de
    # Mobile -> MobileFront settings to only match m|mobile.* routes.
    # Defaults to match m.mealmatch.de
    mobile_req.subdomain: m|mobile
    mobile_def.subdomain: m
    mobile_req.domain: mealmatch|mealmatchapp|frb
    mobile_def.domain: mealmatch
    mobile_req.toplevel: de|local|io
    mobile_def.toplevel: de



    paypal_marketplace:
        live:
            username: ''
            password: ''
            mealmatch_master_token: 'XXX'
        sandbox:
            username: ''
            password: ''
            mealmatch_master_token: 'XXX'

    # GMaps
    gmaps_api_key: AIzaSyC0xceQe_AIz0qbhS4QQtPdRX0022EBALI

    # MangoPay
    mangopay_credentials:
        # the pipeline build should connect to the sandbox
        live: false
        sandbox:
            client_id: '220777'
            client_password: 'cAyY9UqC94SE8zYCnmHJmwPVAonkz2sLCrcbZBuUgQ0A979ZvE'
        production:
            client_id: 'mealmatchgmbhprod'
            # client_password: 'xLWXBMC5QADRK6g0koK3bAOqiAuWzEbQ62SkNokvfTXQftfXXx'
            client_password: 'tjeaFoVzsAZOw1uq2LMVNbKygMZHsgnozG0k9fDvvW6FY496K9'

    database_host: 127.0.0.1
    database_port: 3306
    database_name: mealmatch-pipeline
    database_user: db
    database_password: MM123
    aws3_bucket: mealmatch-stage
    aws3_host: mealmatch-stage.objects.frb.io
    aws3_key: mealmatch-stage
    aws3_region: eu-west-1
    aws3_secret: QWiulrTj44JNkqlnw1S1k2sk9JPo-SyVlfkEj8pt0zPoXRkTdbM1HjwSrfuu_skO
    aws3_server: objects.eu2.frbit.com
    mailer_transport: smtp
    mailer_host: login18.schwarzkuenstler.info
    mailer_user: mailer@mealmatch.de
    mailer_password: 'mvXV%%%x&amp;$!1UfFb'
    facebook_app_id: 1808267089461050
    facebook_secret: 425be9cc5bf772511fec807a61169680
    paypal_credentials:
        app_id: APP-9KN92377EH262120N
        username: mealmatch_api1.steinebach.bi
        password: N7Q25VBLBH8WGRSN
        signature: AiPC9BjkCyDFQXbSkoZcgqH3hpacAqe2RNyOTETm3Xgzbm8xAbAkvqYr
        email: payment@mealmatch.de
        live: false
        sandbox:
            app_id: APP-80W284485P519543T
            username: andre.anneck-facilitator_api1.mealmatch.de
            password: HR5SLLDZM5VGRLMY
            email: mmtest.company@mealmatch.de
            signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A8VATVg.JX2gjB-7T2q3kBzbjmHH
    secret: eb3c36367a865febf98284bfdfe0c7bf7810ec95
    vendor_dir: '%kernel.root_dir%/../vendor'

    router.request_context.host: localhost