services:
    mm_user.registration_subscriber:
        class: MMUserBundle\EventSubscriber\RegistrationSubscriber
        arguments: ["@fos_user.user_manager",  '@logger']
        tags:
            - { name: kernel.event_subscriber }

    mm_user.form.profile:
        class: MMUserBundle\Form\MMProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    mm_user.form.registration:
        class: MMUserBundle\Form\MMRegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    mm_user.image_uploader:
        class: MMUserBundle\Services\ImageUploaderService
        arguments: ['@mm.s3', '@logger', '%aws3_bucket%']