#    mealmatch_calendar.example:
#        class: Mealmatch\CalendarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
   mealmatch_calendar.listener:
        class: Mealmatch\CalendarBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
